kc: 
  url: https://sso-dre002ng-dev.apps.sandbox-m3.1530.p1.openshiftapps.com
  # TODO: use password state to pull the secrets
  username: admin
  password: admin

fetcher_version: 0.0.8
realm_name: ci0-realm